/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Job_Title]
      ,[Salary_Estimate]
      ,[Job_Description]
      ,[Rating]
      ,[Company_Name]
      ,[Location]
      ,[Headquarters]
      ,[Size]
      ,[Founded]
      ,[Type_of_ownership]
      ,[Industry]
      ,[Sector]
      ,[Revenue]
      ,[Competitors]
      ,[Easy_Apply]
  FROM [PortfolioProject].[dbo].[DataAnalyst]